"""
Automated Unit Test Suite for Customer Uplift Modeling & Causal ML Engine.
Verifies Criteo Dataset Ingestion, S-Learner, T-Learner, Doubly Robust AIPW (5-Fold DML),
Known Ground-Truth Causal DGP Sanity, and FastAPI Microservice Endpoints.
"""

import unittest
import os
import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from fastapi.testclient import TestClient

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from src.data_loader import CriteoDataLoader
from src.causal_engine import SingleModelSLearner, TwoModelTLearner, TrueDoublyRobustAIPW
from src.evaluate_metrics import compute_qini_curve
from serve_api import app


class TestCustomerUpliftEngine(unittest.TestCase):
    """
    Comprehensive unit tests for causal uplift models, Qini metrics, ground-truth recovery, and API endpoints.
    """

    @classmethod
    def setUpClass(cls):
        cls.loader = CriteoDataLoader(data_dir="data", sample_size=2000, random_state=42)
        df = cls.loader.load_processed_data()
        
        feature_cols = [f'f{i}' for i in range(12)]
        X = df[feature_cols].values
        T = df['treatment'].values
        Y = df['conversion'].values

        cls.X_train, cls.X_test, cls.T_train, cls.T_test, cls.Y_train, cls.Y_test = train_test_split(
            X, T, Y, test_size=0.25, random_state=42, stratify=T
        )
        cls.api_client = TestClient(app)

    def test_data_loader_partitions(self):
        """Verify feature dimensions, treatment indicator binary values, and target outcome."""
        self.assertGreaterEqual(len(self.X_train), 1000)
        self.assertEqual(self.X_train.shape[1], 12)
        self.assertTrue(set(np.unique(self.T_train)).issubset({0, 1}))
        self.assertTrue(set(np.unique(self.Y_train)).issubset({0, 1}))

    def test_s_learner_fit_and_predict(self):
        """Verify Single-Model S-Learner generates bounded uplift predictions."""
        s_learner = SingleModelSLearner(n_estimators=20, max_depth=3, random_state=42)
        s_learner.fit(self.X_train, self.T_train, self.Y_train)
        preds = s_learner.predict_uplift(self.X_test)

        self.assertEqual(len(preds), len(self.X_test))
        self.assertTrue(np.all(np.isfinite(preds)))
        self.assertTrue(np.all((preds >= -1.0) & (preds <= 1.0)))

    def test_t_learner_fit_and_predict(self):
        """Verify Two-Model T-Learner dual response fitting and prediction."""
        t_learner = TwoModelTLearner(n_estimators=20, max_depth=3, random_state=42)
        t_learner.fit(self.X_train, self.T_train, self.Y_train)
        preds = t_learner.predict_uplift(self.X_test)

        self.assertEqual(len(preds), len(self.X_test))
        self.assertTrue(np.all(np.isfinite(preds)))
        self.assertTrue(np.all((preds >= -1.0) & (preds <= 1.0)))

    def test_doubly_robust_aipw_cross_fitting(self):
        """Verify 3-Fold Cross-Fitting Doubly Robust AIPW CATE model."""
        dr_aipw = TrueDoublyRobustAIPW(n_folds=3, n_estimators=20, max_depth=3, random_state=42)
        dr_aipw.fit(self.X_train, self.T_train, self.Y_train)
        preds = dr_aipw.predict_uplift(self.X_test)

        self.assertEqual(len(preds), len(self.X_test))
        self.assertTrue(np.all(np.isfinite(preds)))

    def test_known_ground_truth_causal_dgp_recovery(self):
        """
        Rigorous Causal Test: Verifies AIPW recovers known ground-truth Average Treatment Effect (ATE).
        DGP: True CATE tau(X) = 0.08 + 0.04 * X0 => True ATE approx 0.08.
        """
        np.random.seed(42)
        n_synth = 3000
        X_synth = np.random.normal(0, 1, size=(n_synth, 12))
        T_synth = (np.random.rand(n_synth) < 0.50).astype(int)  # 50/50 RCT
        
        true_cate = 0.08 + 0.04 * X_synth[:, 0]
        base_rate = 0.20 + 0.10 * X_synth[:, 1]
        
        prob_y = (base_rate + T_synth * true_cate).clip(0.01, 0.99)
        Y_synth = (np.random.rand(n_synth) < prob_y).astype(int)
        
        aipw = TrueDoublyRobustAIPW(n_folds=3, n_estimators=30, learning_rate=0.05, max_depth=3, random_state=42)
        aipw.fit(X_synth, T_synth, Y_synth)
        pred_cate = aipw.predict_uplift(X_synth)
        
        estimated_ate = float(np.mean(pred_cate))
        true_ate = float(np.mean(true_cate))
        
        # Assert estimated ATE is within strict tolerance (+/- 0.035) of ground truth
        self.assertAlmostEqual(estimated_ate, true_ate, delta=0.035,
                               msg=f"AIPW failed ground-truth recovery: Estimated ATE {estimated_ate:.4f} vs True {true_ate:.4f}")

    def test_qini_and_auuc_positive_lift_on_known_effect(self):
        """Verify that Qini curve generated by model on causal data achieves positive Qini lift over random baseline."""
        np.random.seed(42)
        n = 1000
        X = np.random.randn(n, 12)
        T = (np.random.rand(n) < 0.5).astype(int)
        true_uplift = 0.10 * X[:, 0]
        Y = (np.random.rand(n) < (0.2 + T * true_uplift).clip(0, 1)).astype(int)
        
        # Perfect ranking vs Random
        qini_curve, random_curve, auuc, qini_lift = compute_qini_curve(Y, T, true_uplift, n_bins=10)
        self.assertEqual(len(qini_curve), 11)
        self.assertGreater(qini_lift, 0.0, "Model should achieve positive Qini lift on known causal effect")

    def test_fastapi_health_endpoint(self):
        """Verify FastAPI /health endpoint returns 200 and healthy payload."""
        response = self.api_client.get("/health")
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertEqual(data["status"], "HEALTHY")
        self.assertIn("model_name", data)

    def test_fastapi_predict_uplift_endpoint(self):
        """Verify FastAPI /predict_uplift returns valid CATE, segment, and action."""
        payload = {"features": [0.1] * 12}
        response = self.api_client.post("/predict_uplift", json=payload)
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertIn("predicted_cate_uplift", data)
        self.assertIn("customer_segment", data)
        self.assertIn("prescribed_action", data)
        self.assertIn("inference_time_ms", data)

    def test_fastapi_validation_error(self):
        """Verify FastAPI returns 422 for invalid feature dimensions."""
        payload = {"features": [0.1] * 5}  # 5 features instead of 12
        response = self.api_client.post("/predict_uplift", json=payload)
        self.assertEqual(response.status_code, 422)


if __name__ == '__main__':
    unittest.main()
